name: build-and-tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '16.x'
            cache: nmp
      - run: npm install
      - run: make setup
      - run: make test
      - run: make lint
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: 810786af-82da-4d5c-a49d-59227fa84c36
        with:
          args: --severity-threshold=high